<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>Fantastic_Fist_Archipelago_Client</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>Fantastic_Fist_Archipelago_Client</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <EmbeddedResource Remove="AP World\**" />
	  <None Remove="AP World\**" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="E7.Introloop">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\E7.Introloop.dll</HintPath>
		</Reference>
		<Reference Include="Mono.Posix">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\Mono.Posix.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ARModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ARModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Networking">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.Networking.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticlesLegacyModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ParticlesLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpatialTracking">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.SpatialTracking.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StandardEvents">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.StandardEvents.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StyleSheetsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.StyleSheetsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Timeline">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.Timeline.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UNETModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UNETModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WebModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.WebModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
			<HintPath>$(GamePath)/FantasticFist_Data\Managed\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)/MelonLoader\net35\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)/MelonLoader\net35\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="ValueTupleBridge">
			<HintPath>$(GamePath)/MelonLoader\net35\ValueTupleBridge.dll</HintPath>
		</Reference>

	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Core.cs" />
		<Compile Include="ItemManager.cs" />
		<Compile Include="LocationManager.cs" />
		<Compile Include="Locker.cs" />
		<Compile Include="MessageManager.cs" />
		<Compile Include="Patcher.cs" />
		<Compile Include="PathManager.cs" />
		<Content Include="Directory.Build.props" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(GamePath)/Mods&quot;" />
	</Target>
</Project>