from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import ItemClassification, Location

from . import items, regions

if TYPE_CHECKING:
    from .world import FantasticFistWorld

LOCATION_NAME_TO_ID = {
    # Coins
    "Introduction Coin 1": 1,
    "Introduction Coin 2": 2,
    "The Caves Coin 1": 3,
    "The Caves Coin 2": 4,
    "The Caves Coin 3": 5,
    "Get A Grip Coin 1": 6,
    "Verticality Coin 1": 7,
    "Verticality Coin 2": 8,
    "Verticality Coin 3": 9,
    "Catch A Ride Coin 1": 10,
    "Catch A Ride Coin 2": 11,
    "Catch A Ride Coin 3": 12,
    "Chaos Cavern Coin 1": 13,
    "Holding On Coin 1": 14,
    "Cliff Warning Coin 1": 15,
    "The Library Coin 1": 16,
    "The Library Coin 2": 17,
    "The Library Coin 3": 18,
    "Midnight Grove Coin 1": 19,
    "Midnight Grove Coin 2": 20,
    "Midnight Grove Coin 3": 21,
    "Briarbrush Woods Coin 1": 22,
    "Various Explosives Coin 1": 23,
    "Various Explosives Coin 2": 24,
    "Various Explosives Coin 3": 25,
    "Together By Tether Coin 1": 26,
    "Together By Tether Coin 2": 27,
    "Together By Tether Coin 3": 28,
    "Pop Unlock Coin 1": 29,
    "Pop Unlock Coin 2": 30,
    "The Gatekeeper Coin 1": 31,
    "The Gatekeeper Coin 2": 32,
    "The Gatekeeper Coin 3": 33,
    "The Elevator Coin 1": 34,
    "Frostbite Coin 1": 35,
    "Forgotten Archives Coin 1": 36,
    "Forgotten Archives Coin 2": 37,
    "The Scenic Route Coin 1": 38,
    "The Timeless Temple Coin 1": 39,
    "Haunted Halls Coin 1": 40,
    "Borrowed Time Coin 1": 41,
    "Nyctophobia Coin 1": 42,
    "Nyctophobia Coin 2": 43,
    "Nyctophobia Coin 3": 44,
    "Nyctophobia Coin 4": 45,
    "Nyctophobia Coin 5": 46,
    "Shifting Walls Coin 1": 47,
    "Shifting Walls Coin 2": 48,
    "Skullduggery Coin 1": 49,
    "Skullduggery Coin 2": 50,
    "Skullduggery Coin 3": 51,
    "Skullduggery Coin 4": 52,
    "The Throne Room Coin 1": 53,
    "The Throne Room Coin 2": 54,
    "The Throne Room Coin 3": 55,
    "Pop To The Top Coin 1": 56,
    "Pop To The Top Coin 2": 57,
    "Periodic Prison Coin 1": 58,
    "Periodic Prison Coin 2": 59,
    "Infinity Garden Coin 1": 60,
    "Infinity Garden Coin 2": 61,
    "Infinity Garden Coin 3": 62,
    "Autumnal Aether Coin 1": 63,
    "Autumnal Aether Coin 2": 64,
    "Autumnal Aether Coin 3": 65,
    "Autumnal Aether Coin 4": 66,
    "Autumnal Aether Coin 5": 67,
    "Among The Stars Coin 1": 68,
    "Among The Stars Coin 2": 69,
    "Den Of Pixies Coin 1": 70,
    "Den Of Pixies Coin 2": 71,
    "Den Of Pixies Coin 3": 72,
    "Heels Over Head Coin 1": 73,
    "The Hive Coin 1": 74,
    "The Hive Coin 2": 75,
    "The Hive Coin 3": 76,
    "The Five Mile Spire Coin 1": 77,
    "The Five Mile Spire Coin 2": 78,
    "The Five Mile Spire Coin 3": 79,
    "The Five Mile Spire Coin 4": 80,
    "The Five Mile Spire Coin 5": 81,
    "Gube Gardens Coin 1": 82,
    "Gube Gardens Coin 2": 83,
    "Gube Gardens Coin 3": 84,
    "The Golf Fungus Coin 1": 85,
    "Over The Woods Coin 1": 86,
    "Welcome To The Void Coin 1": 87,
    "Welcome To The Void Coin 2": 88,
    "Welcome To The Void Coin 3": 89,
    "Welcome To The Void Coin 4": 90,
    "Welcome To The Void Coin 5": 91,
    "The Sky Is Falling Coin 1": 92,
    "The Sky Is Falling Coin 2": 93,
    "The Sky Is Falling Coin 3": 94,
    "The Sky Is Falling Coin 4": 95,
    "The Sky Is Falling Coin 5": 96,
    "The Looking Glass Coin 1": 97,
    "The Looking Glass Coin 2": 98,
    "The Looking Glass Coin 3": 99,
    "The Looking Glass Coin 4": 100,
    # Level Exits
    "Introduction Level Clear": 130,
    "The Caves Level Clear": 131,
    "The Caves Load Bearing Collectible": 132,
    "Get A Grip Level Clear": 133,
    "Verticality Level Clear": 134,
    "Verticality Load Bearing Collectible": 135,
    "Catch A Ride Level Clear": 136,
    "Chaos Cavern Level Clear": 137,
    "Holding On Level Clear": 138,
    "Fist Fight Level Clear": 139,
    "Depths Level Clear": 140,
    "Cliff Warning Level Clear": 141,
    "The Library Level Clear": 142,
    "Midnight Grove Level Clear": 143,
    "Midnight Grove Load Bearing Collectible": 144,
    "Briarbrush Woods Level Clear": 145,
    "Various Explosives Level Clear": 146,
    "Together By Tether Level Clear": 147,
    "Pop Unlock Level Clear": 148,
    "The Gatekeeper Level Clear": 149,
    "The Elevator Level Clear": 150,
    "Frostbite Level Clear": 151,
    "Forgotten Archives Level Clear": 152,
    "Forgotten Archives Load Bearing Collectible": 153,
    "The Scenic Route Level Clear": 154,
    "The Timeless Temple Level Clear": 155,
    "The Timeless Temple Load Bearing Collectible": 156,
    "Haunted Halls Level Clear": 157,
    "Borrowed Time Level Clear": 158,
    "Nyctophobia Level Clear": 159,
    "Shifting Walls Level Clear": 160,
    "Skullduggery Level Clear": 161,
    "The Throne Room Level Clear": 162,
    "Pop To The Top Level Clear": 163,
    "Periodic Prison Level Clear": 164,
    "Infinity Garden Level Clear": 165,
    "Infinity Garden Load Bearing Collectible": 166,
    "Autumnal Aether Level Clear": 167,
    "Among The Stars Level Clear": 168,
    "Den Of Pixies Level Clear": 169,
    "Heels Over Head Level Clear": 170,
    "The Hive Level Clear": 171,
    "The Five Mile Spire Level Clear": 172,
    "Gube Gardens Level Clear": 173,
    "The Golf Fungus Level Clear": 174,
    "Over The Woods Level Clear": 175,
    "Welcome To The Void Level Clear": 176,
    "The Sky Is Falling Level Clear": 177,
    "The Looking Glass Level Clear": 178,
    "The Looking Glass Universal Bearing Collectible": 179,
    "Galactic Central Point Level Clear": 180,
    "Home Level Clear": 181,
    # Tutorial Pages
    "Coyote Time Tutorial": 200,
    "Box Boosting Tutorial": 201,
    "Fast Falling Tutorial": 202,
    "Steep Slope Kicks Tutorial": 203,
    "Bubble Jumps Tutorial": 204,
    "Fireworks Tutorial": 205,
    #Tutorial Panels
    "Verticality Tutorial Panel": 250,
    "The Library Tutorial Panel 1": 251,
    "The Library Tutorial Panel 2": 252,
    "The Library Tutorial Panel 3": 253,
    "Forgotten Archives Tutorial Panel": 254,
    "Autumnal Aether Tutorial Panel": 255,
    "Welcome To The Void Tutorial Panel": 256,
    #Boss Hits
    "Fist Fight Heart 1": 300,
    "Fist Fight Heart 2": 301,
    "Fist Fight Heart 3": 302,
    "The Gatekeeper Heart 1": 310,
    "The Gatekeeper Heart 2": 311,
    "The Gatekeeper Heart 3": 312,
    "The Gatekeeper Heart 4": 313,
    "The Throne Room Heart 1": 320,
    "The Throne Room Heart 2": 321,
    "The Throne Room Heart 3": 322,
    "The Golf Fungus Hole 1": 330,
    "The Golf Fungus Hole 2": 331,
    "The Golf Fungus Hole 3": 332,
    "The Golf Fungus Hole 4": 333,
    "The Golf Fungus Hole 5": 334,
    "The Golf Fungus Hole 6": 335,
    "The Golf Fungus Hole 7": 336,
    "The Golf Fungus Hole 8": 337,
    "The Golf Fungus Hole 9": 338,
    "Galactic Central Point Heart 32": 340,
    "Galactic Central Point Heart 49": 341,
    "Galactic Central Point Heart 37": 342,
    # Rooms
    # World 1
    "Introduction Room 1": 400,
    "Introduction Room 2": 401,
    "Introduction Room 3": 402,
    "Introduction Room 4": 403,
    "The Caves Room 1": 404,
    "The Caves Room 2": 405,
    "The Caves Room 3": 406,
    "The Caves Room 4": 407,
    "Get A Grip Room 1": 408,
    "Get A Grip Room 2": 409,
    "Get A Grip Room 3": 410,
    "Verticality Room 1": 411,
    "Verticality Room 2": 412,
    "Verticality Room 2b": 413,
    "Verticality Room 3": 414,
    "Verticality Room 4": 415,
    "Catch A Ride Room 1": 416,
    "Catch A Ride Room 2": 417,
    "Catch A Ride Room 3": 418,
    "Catch A Ride Room 4": 419,
    "Chaos Cavern Room 1": 420,
    "Chaos Cavern Room 2": 421,
    "Chaos Cavern Room 3": 422,
    "Holding On Room 1": 423,
    "Holding On Room 2": 424,
    "Holding On Room 3": 425,
    "Holding On Room 4": 426,
    "Fist Fight Room 1": 427,
    "Fist Fight Room 2": 428,
    "Fist Fight Room 3": 429,
    "Fist Fight Room 4": 430,
    "Fist Fight Room 5": 431,
    "Fist Fight Boss Arena": 432,
    "Depths Room 1": 433,
    "Depths Room 2": 434,
    "Depths Room 3": 435,
    "Cliff Warning Room 1": 436,
    "Cliff Warning Room 2": 437,
    "The Library Room 1": 438,
    "The Library Room 1b": 439,
    "The Library Room 1c": 440,
    "The Library Room 1d": 441,
    # World 2
    "Midnight Grove Room 1": 500,
    "Midnight Grove Room 2": 501,
    "Midnight Grove Room 3": 502,
    "Midnight Grove Room 4": 503,
    "Briarbrush Woods Room 1": 504,
    "Briarbrush Woods Room 2": 505,
    "Briarbrush Woods Room 3": 506,
    "Briarbrush Woods Room 4": 507,
    "Various Explosives Room 1": 508,
    "Various Explosives Room 2": 509,
    "Various Explosives Room 3": 510,
    "Together By Tether Room 1": 511,
    "Together By Tether Room 2": 512,
    "Together By Tether Room 3": 513,
    "Together By Tether Room 4": 514,
    "Pop Unlock Room 1": 515,
    "Pop Unlock Room 2": 516,
    "Pop Unlock Room 3": 517,
    "The Gatekeeper Room 1": 518,
    "The Gatekeeper Room 2": 519,
    "The Gatekeeper Room 3": 520,
    "The Gatekeeper Room 4": 521,
    "The Gatekeeper Boss Arena": 522,
    "The Elevator Room 1": 523,
    "The Elevator Room 2": 524,
    "The Elevator Room 3": 525,
    "Frostbite Room 1": 526,
    "Frostbite Room 2": 527,
    "Frostbite Room 3": 528,
    "Frostbite Room 4": 529,
    "Forgotten Archives Room 1": 530,
    "Forgotten Archives Room 2": 531,
    "Forgotten Archives Room 3": 532,
    "Forgotten Archives Room 4": 533,
    "Forgotten Archives Room 5": 534,
    "The Scenic Route Room 1": 535,
    "The Scenic Route Room 2": 536,
    "The Scenic Route Room 3": 537,
    "The Scenic Route Room 4": 538,
    "The Scenic Route Room 5": 539,
    "The Scenic Route Room 6": 540,
    "The Scenic Route Room 7": 541,
    # World 3
    "The Timeless Temple Room 1": 600,
    "The Timeless Temple Room 2": 601,
    "The Timeless Temple Room 3": 602,
    "Haunted Halls Room 1": 603,
    "Haunted Halls Room 2": 604,
    "Haunted Halls Room 3": 605,
    "Haunted Halls Room 4": 606,
    "Borrowed Time Room 1": 607,
    "Borrowed Time Room 2": 608,
    "Borrowed Time Room 3": 609,
    "Borrowed Time Room 4": 610,
    "Nyctophobia Room 1": 611,
    "Nyctophobia Room 2": 612,
    "Nyctophobia Room 3": 613,
    "Nyctophobia Room 4": 614,
    "Nyctophobia Room 5": 615,
    "Shifting Walls Room 1": 616,
    "Shifting Walls Room 2": 617,
    "Shifting Walls Room 3": 618,
    "Shifting Walls Room 4": 619,
    "Skullduggery Room 1": 620,
    "Skullduggery Room 2": 621,
    "Skullduggery Room 3": 622,
    "Skullduggery Room 4": 623,
    "Skullduggery Room 5": 624,
    "The Throne Room Room 1": 625,
    "The Throne Room Room 2": 626,
    "The Throne Room Room 3": 627,
    "The Throne Room Room 4a": 628,
    "The Throne Room Room 4b": 629,
    "The Throne Room Room 5": 630,
    "The Throne Room Room 6a": 631,
    "The Throne Room Room 6b": 632,
    "The Throne Room Room 7": 633,
    "The Throne Room Boss Arena": 634,
    "The Throne Room Room 8": 635,
    "Pop To The Top Room 1": 636,
    "Pop To The Top Room 2": 637,
    "Pop To The Top Room 3": 638,
    "Periodic Prison Room 1": 639,
    "Periodic Prison Room 2": 640,
    "Periodic Prison Room 3": 641,
    "Periodic Prison Room 4": 642,
    # World 4
    "Infinity Garden Room 1": 700,
    "Infinity Garden Room 2": 701,
    "Infinity Garden Room 3": 702,
    "Autumnal Aether Room 1": 703,
    "Autumnal Aether Room 2": 704,
    "Autumnal Aether Room 3": 705,
    "Among The Stars Room 1": 706,
    "Among The Stars Room 2": 707,
    "Among The Stars Room 3": 708,
    "Among The Stars Room 4": 709,
    "Den Of Pixies Room 1": 710,
    "Den Of Pixies Room 2": 711,
    "Den Of Pixies Room 3": 712,
    "Den Of Pixies Room 4": 713,
    "Heels Over Head Room 1": 714,
    "Heels Over Head Room 2": 715,
    "Heels Over Head Room 3": 716,
    "Heels Over Head Room 4": 717,
    "The Hive Room 1": 718,
    "The Hive Room 2": 719,
    "The Hive Room 3": 720,
    "The Hive Room 4": 721,
    "The Hive Room 5": 722,
    "The Hive Room 6": 723,
    "The Hive Room 7": 724,
    "The Five Mile Spire Room 1": 725,
    "The Five Mile Spire Room 2": 726,
    "The Five Mile Spire Room 3": 727,
    "The Five Mile Spire Room 4": 728,
    "The Five Mile Spire Room 5": 729,
    "The Five Mile Spire Room 6": 730,
    "The Five Mile Spire Room 7": 731,
    "The Five Mile Spire Room 7b": 732,
    "The Five Mile Spire Room 8": 733,
    "Gube Gardens Room 1": 734,
    "Gube Gardens Room 2": 735,
    "Gube Gardens Room 3": 736,
    "Gube Gardens Room 4": 737,
    "Gube Gardens Room 5": 738,
    "The Golf Fungus Room 1": 739,
    "The Golf Fungus Room 2": 740,
    "The Golf Fungus Room 3": 741,
    "The Golf Fungus Room 4": 742,
    "The Golf Fungus Room 5": 743,
    "The Golf Fungus Room 6": 744,
    "The Golf Fungus Room 7": 745,
    "The Golf Fungus Room 8": 746,
    "The Golf Fungus Room 9": 747,
    "The Golf Fungus Room 10": 748,
    "The Golf Fungus Room 11": 749,
    "Over The Woods Room 1": 750,
    "Over The Woods Room 2": 751,
    "Over The Woods Room 3": 752,
    # World 5
    "Welcome To The Void Room 1": 800,
    "Welcome To The Void Room 2": 801,
    "Welcome To The Void Room 3": 802,
    "Welcome To The Void Room 4": 803,
    "Welcome To The Void Room 5": 804,
    "The Sky Is Falling Room 1": 805,
    "The Sky Is Falling Room 2": 806,
    "The Sky Is Falling Room 3": 807,
    "The Sky Is Falling Room 4": 808,
    "The Sky Is Falling Room 5": 809,
    "The Looking Glass Room 1": 810,
    "The Looking Glass Room 2": 811,
    "The Looking Glass Room 3": 812,
    "The Looking Glass Room 4": 813,
    "The Looking Glass Room 5": 814,
    "Galactic Central Point Room 1": 815,
    "Galactic Central Point Room 2": 816,
    "Galactic Central Point Room 3": 817,
    "Galactic Central Point Boss Arena 32": 818,
    "Galactic Central Point Boss Arena 49": 819,
    "Galactic Central Point Boss Arena 37": 820,
    "Universal Bearing Collectible The Hive": 821,
    "Universal Bearing Collectible Nyctophobia": 822,
    "Universal Bearing Collectible Various Explosives": 823,
    "Universal Bearing Collectible Introduction": 824,
    "Home Room 1": 825,
    "Home Room 2": 826,
    "Home Room 3": 827,
    "Home Room 4": 828,
    "Home Room 5": 829,
    "Home Room 6": 830,
    # Checkpoints
    "Introduction Checkpoint 1": 900,
    "The Caves Checkpoint 1": 901,
    "The Caves Checkpoint 2": 902,
    "Get A Grip Checkpoint 1": 903,
    "Get A Grip Checkpoint 2": 904,
    "Verticality Checkpoint 1": 905,
    "Catch A Ride Checkpoint 1": 906,
    "Holding On Checkpoint 1": 907,
    "Holding On Checkpoint 2": 908,
    "Cliff Warning Checkpoint 1": 909,
    "Midnight Grove Checkpoint 1": 910,
    "Midnight Grove Checkpoint 2": 911,
    "Frostbite Checkpoint 1": 912,
    "Forgotten Archives Checkpoint 1": 913,
    "Forgotten Archives Checkpoint 2": 914,
    "Forgotten Archives Checkpoint 3": 915,
    "The Scenic Route Checkpoint 1": 916,
    "Nyctophobia Checkpoint 1": 917,
    "Shifting Walls Checkpoint 1": 918,
    "Shifting Walls Checkpoint 2": 919,
    "Autumnal Aaether Checkpoint 1": 920,
    "Autumnal Aaether Checkpoint 2": 921,
    "Among The Stars Checkpoint 1": 922,
    "Heels Over Head Checkpoint 1": 923,
    "The Hive Checkpoint 1": 924,
    "The Hive Checkpoint 2": 925,
    "Welcome To The Void Checkpoint 1": 926,
    "Welcome To The Void Checkpoint 2": 927,
    "The Looking Glass Checkpoint 1": 928,
    "Galactic Central Point Checkpoint 1": 929,
    "Universal Bearing Collectable Checkpoint 1": 930,
    "Universal Bearing Collectable Checkpoint 2": 931,
    "Universal Bearing Collectable Checkpoint 3": 932,
    "Universal Bearing Collectable Checkpoint 4": 933,
    "Home Checkpoint 1": 934,
    "Home Checkpoint 2": 935,
    "Home Checkpoint 3": 936,
    "Home Checkpoint 4": 937,
    "Home Checkpoint 5": 938,
    "Home Checkpoint 6": 939,
    "Home Checkpoint 7": 940,
    "Home Checkpoint 8": 941
}

ID_TO_LOCATION_NAME = {v: k for k, v in LOCATION_NAME_TO_ID.items()}

LOCATION_NAME_TO_REGION = {
    # Coins
    "Introduction Coin 1": "Introduction Room 2",
    "Introduction Coin 2": "Introduction Room 4",
    "The Caves Coin 1": "The Caves Room 1",
    "The Caves Coin 2": "The Caves Room 3",
    "The Caves Coin 3": "The Caves Room 4",
    "Get A Grip Coin 1": "Get A Grip Room 1",
    "Verticality Coin 1": "Verticality Room 2",
    "Verticality Coin 2": "Verticality Room 2B",
    "Verticality Coin 3": "Verticality Room 4",
    "Catch A Ride Coin 1": "Catch A Ride Room 2",
    "Catch A Ride Coin 2": "Catch A Ride Room 3",
    "Catch A Ride Coin 3": "Catch A Ride Room 3",
    "Chaos Cavern Coin 1": "Chaos Cavern Room 3",
    "Holding On Coin 1": "Holding On Room 4",
    "Cliff Warning Coin 1": "Cliff Warning Room 2",
    "The Library Coin 1": "The Library Room 1B",
    "The Library Coin 2": "The Library Room 1C",
    "The Library Coin 3": "The Library Room 1D",
    "Midnight Grove Coin 1": "Midnight Grove Room 1",
    "Midnight Grove Coin 2": "Midnight Grove Room 2",
    "Midnight Grove Coin 3": "Midnight Grove Room 3",
    "Briarbrush Woods Coin 1": "Briarbrush Woods Room 2",
    "Various Explosives Coin 1": "Various Explosives Room 1",
    "Various Explosives Coin 2": "Various Explosives Room 2",
    "Various Explosives Coin 3": "Various Explosives Room 3",
    "Together By Tether Coin 1": "Together By Tether Room 2",
    "Together By Tether Coin 2": "Together By Tether Room 2",
    "Together By Tether Coin 3": "Together By Tether Room 3",
    "Pop Unlock Coin 1": "Pop Unlock Room 2",
    "Pop Unlock Coin 2": "Pop Unlock Room 3",
    "The Gatekeeper Coin 1": "The Gatekeeper Room 3",
    "The Gatekeeper Coin 2": "The Gatekeeper Room 3",
    "The Gatekeeper Coin 3": "The Gatekeeper Room 4",
    "The Elevator Coin 1": "The Elevator Room 3",
    "Frostbite Coin 1": "Frostbite Room 3",
    "Forgotten Archives Coin 1": "Forgotten Archives Room 3",
    "Forgotten Archives Coin 2": "Forgotten Archives Room 5",
    "The Scenic Route Coin 1": "The Scenic Route Room 7",
    "The Timeless Temple Coin 1": "The Timeless Temple Room 3",
    "Haunted Halls Coin 1": "Haunted Halls Room 2",
    "Borrowed Time Coin 1": "Borrowed Time Room 2",
    "Nyctophobia Coin 1": "Nyctophobia Room 1",
    "Nyctophobia Coin 2": "Nyctophobia Room 2",
    "Nyctophobia Coin 3": "Nyctophobia Room 3",
    "Nyctophobia Coin 4": "Nyctophobia Room 4",
    "Nyctophobia Coin 5": "Nyctophobia Room 5",
    "Shifting Walls Coin 1": "Shifting Walls Room 3",
    "Shifting Walls Coin 2": "Shifting Walls Room 4",
    "Skullduggery Coin 1": "Skullduggery Room 2",
    "Skullduggery Coin 2": "Skullduggery Room 2",
    "Skullduggery Coin 3": "Skullduggery Room 3",
    "Skullduggery Coin 4": "Skullduggery Room 5",
    "The Throne Room Coin 1": "The Throne Room Room 2",
    "The Throne Room Coin 2": "The Throne Room Room 5",
    "The Throne Room Coin 3": "The Throne Room Room 8",
    "Pop To The Top Coin 1": "Pop To The Top Room 1",
    "Pop To The Top Coin 2": "Pop To The Top Room 2",
    "Periodic Prison Coin 1": "Periodic Prison Room 4",
    "Periodic Prison Coin 2": "Periodic Prison Room 4",
    "Infinity Garden Coin 1": "Infinity Garden Room 1",
    "Infinity Garden Coin 2": "Infinity Garden Room 2",
    "Infinity Garden Coin 3": "Infinity Garden Room 3",
    "Autumnal Aether Coin 1": "Autumnal Aether Room 1",
    "Autumnal Aether Coin 2": "Autumnal Aether Room 1",
    "Autumnal Aether Coin 3": "Autumnal Aether Room 1",
    "Autumnal Aether Coin 4": "Autumnal Aether Room 3",
    "Autumnal Aether Coin 5": "Autumnal Aether Room 3",
    "Among The Stars Coin 1": "Among The Stars Room 1",
    "Among The Stars Coin 2": "Among The Stars Room 2",
    "Den Of Pixies Coin 1": "Den Of Pixies Room 2",
    "Den Of Pixies Coin 2": "Den Of Pixies Room 3",
    "Den Of Pixies Coin 3": "Den Of Pixies Room 4",
    "Heels Over Head Coin 1": "Heels Over Head Room 3",
    "The Hive Coin 1": "The Hive Room 2",
    "The Hive Coin 2": "The Hive Room 3",
    "The Hive Coin 3": "The Hive Room 5",
    "The Five Mile Spire Coin 1": "The Five Mile Spire Room 2",
    "The Five Mile Spire Coin 2": "The Five Mile Spire Room 3",
    "The Five Mile Spire Coin 3": "The Five Mile Spire Room 3",
    "The Five Mile Spire Coin 4": "The Five Mile Spire Room 7",
    "The Five Mile Spire Coin 5": "The Five Mile Spire Room 8",
    "Gube Gardens Coin 1": "Gube Gardens Room 1",
    "Gube Gardens Coin 2": "Gube Gardens Room 2",
    "Gube Gardens Coin 3": "Gube Gardens Room 5",
    "The Golf Fungus Coin 1": "The Golf Fungus Room 11",
    "Over The Woods Coin 1": "Over The Woods Room 3",
    "Welcome To The Void Coin 1": "Welcome To The Void Room 1",
    "Welcome To The Void Coin 2": "Welcome To The Void Room 3",
    "Welcome To The Void Coin 3": "Welcome To The Void Room 3",
    "Welcome To The Void Coin 4": "Welcome To The Void Room 4",
    "Welcome To The Void Coin 5": "Welcome To The Void Room 5",
    "The Sky Is Falling Coin 1": "The Sky Is Falling Room 1",
    "The Sky Is Falling Coin 2": "The Sky Is Falling Room 2",
    "The Sky Is Falling Coin 3": "The Sky Is Falling Room 3",
    "The Sky Is Falling Coin 4": "The Sky Is Falling Room 5",
    "The Sky Is Falling Coin 5": "The Sky Is Falling Room 5",
    "The Looking Glass Coin 1": "The Looking Glass Room 2",
    "The Looking Glass Coin 2": "The Looking Glass Room 3",
    "The Looking Glass Coin 3": "The Looking Glass Room 3",
    "The Looking Glass Coin 4": "The Looking Glass Room 4",
    # Level Exits
    "Introduction Level Clear": "Introduction Room 4",
    "The Caves Level Clear": "The Caves Room 4",
    "The Caves Load Bearing Collectible": "The Caves Room 2",
    "Get A Grip Level Clear": "Get A Grip Room 3",
    "Verticality Level Clear": "Verticality Room 4",
    "Verticality Load Bearing Collectible": "Verticality Room 2",
    "Catch A Ride Level Clear": "Catch A Ride Room 4",
    "Chaos Cavern Level Clear": "Chaos Cavern Room 3",
    "Holding On Level Clear": "Holding On Room 4",
    "Fist Fight Level Clear": "Fist Fight Boss Arena",
    "Depths Level Clear": "Depths Room 3",
    "Cliff Warning Level Clear": "Cliff Warning Room 2",
    "The Library Level Clear": "The Library Room 1",
    "Midnight Grove Level Clear": "Midnight Grove Room 4",
    "Midnight Grove Load Bearing Collectible": "Midnight Grove Room 4",
    "Briarbrush Woods Level Clear": "Briarbrush Woods Room 4",
    "Various Explosives Level Clear": "Various Explosives Room 3",
    "Together By Tether Level Clear": "Together By Tether Room 4",
    "Pop Unlock Level Clear": "Pop Unlock Room 3",
    "The Gatekeeper Level Clear": "The Gatekeeper Boss Arena",
    "The Elevator Level Clear": "The Elevator Room 3",
    "Frostbite Level Clear": "Frostbite Room 4",
    "Forgotten Archives Level Clear": "Forgotten Archives Room 5",
    "Forgotten Archives Load Bearing Collectible": "Forgotten Archives Room 4",
    "The Scenic Route Level Clear": "The Scenic Route Room 7",
    "The Timeless Temple Level Clear": "The Timeless Temple Room 3",
    "The Timeless Temple Load Bearing Collectible": "The Timeless Temple Room 3",
    "Haunted Halls Level Clear": "Haunted Halls Room 4",
    "Borrowed Time Level Clear": "Borrowed Time Room 4",
    "Nyctophobia Level Clear": "Nyctophobia Room 5",
    "Shifting Walls Level Clear": "Shifting Walls Room 4",
    "Skullduggery Level Clear": "Skullduggery Room 5",
    "The Throne Room Level Clear": "The Throne Room Room 8",
    "Pop To The Top Level Clear": "Pop To The Top Room 3",
    "Periodic Prison Level Clear": "Periodic Prison Room 4",
    "Infinity Garden Level Clear": "Infinity Garden Room 3",
    "Infinity Garden Load Bearing Collectible": "Infinity Garden Room 3",
    "Autumnal Aether Level Clear": "Autumnal Aether Room 3",
    "Among The Stars Level Clear": "Among The Stars Room 4",
    "Den Of Pixies Level Clear": "Den Of Pixies Room 4",
    "Heels Over Head Level Clear": "Heels Over Head Room 4",
    "The Hive Level Clear": "The Hive Room 7",
    "The Five Mile Spire Level Clear": "The Five Mile Spire Room 8",
    "Gube Gardens Level Clear": "Gube Gardens Room 5",
    "The Golf Fungus Level Clear": "The Golf Fungus Room 11",
    "Over The Woods Level Clear": "Over The Woods Room 3",
    "Welcome To The Void Level Clear": "Welcome To The Void Room 5",
    "The Sky Is Falling Level Clear": "The Sky Is Falling Room 5",
    "The Looking Glass Level Clear": "The Looking Glass Room 5",
    "The Looking Glass Universal Bearing Collectible": "Universal Bearing Collectible Introduction",
    "Galactic Central Point Level Clear": "Galactic Central Point Boss Arena 37",
    "Home Level Clear": "Home Room 5",
    # Tutorial Pages
    "Coyote Time Tutorial": "Menu",
    "Box Boosting Tutorial": "Menu",
    "Fast Falling Tutorial": "Menu",
    "Steep Slope Kicks Tutorial": "Menu",
    "Bubble Jumps Tutorial": "Menu",
    "Fireworks Tutorial": "Menu",
    #Tutorial Panels
    "Verticality Tutorial Panel": "Verticality Room 2B",
    "The Library Tutorial Panel 1": "The Library Room 1",
    "The Library Tutorial Panel 2": "The Library Room 1",
    "The Library Tutorial Panel 3": "The Library Room 1",
    "Forgotten Archives Tutorial Panel": "Forgotten Archives Room 2",
    "Autumnal Aether Tutorial Panel": "Autumnal Aether Room 2",
    "Welcome To The Void Tutorial Panel": "Welcome To The Void Room 2",
    #Boss Hits
    "Fist Fight Heart 1": "Fist Fight Boss Arena",
    "Fist Fight Heart 2": "Fist Fight Boss Arena",
    "Fist Fight Heart 3": "Fist Fight Boss Arena",
    "The Gatekeeper Heart 1": "The Gatekeeper Boss Arena",
    "The Gatekeeper Heart 2": "The Gatekeeper Boss Arena",
    "The Gatekeeper Heart 3": "The Gatekeeper Boss Arena",
    "The Gatekeeper Heart 4": "The Gatekeeper Boss Arena",
    "The Throne Room Heart 1": "The Throne Room Boss Arena",
    "The Throne Room Heart 2": "The Throne Room Boss Arena",
    "The Throne Room Heart 3": "The Throne Room Boss Arena",
    "The Golf Fungus Hole 1": "The Golf Fungus Room 2",
    "The Golf Fungus Hole 2": "The Golf Fungus Room 3",
    "The Golf Fungus Hole 3": "The Golf Fungus Room 4",
    "The Golf Fungus Hole 4": "The Golf Fungus Room 5",
    "The Golf Fungus Hole 5": "The Golf Fungus Room 6",
    "The Golf Fungus Hole 6": "The Golf Fungus Room 7",
    "The Golf Fungus Hole 7": "The Golf Fungus Room 8",
    "The Golf Fungus Hole 8": "The Golf Fungus Room 9",
    "The Golf Fungus Hole 9": "The Golf Fungus Room 10",
    "Galactic Central Point Heart 32": "Galactic Central Point Boss Arena 32",
    "Galactic Central Point Heart 49": "Galactic Central Point Boss Arena 49",
    "Galactic Central Point Heart 37": "Galactic Central Point Boss Arena 37",
    # Rooms
    # World 1
    "Introduction Room 1": "Introduction Room 1",
    "Introduction Room 2": "Introduction Room 2",
    "Introduction Room 3": "Introduction Room 3",
    "Introduction Room 4": "Introduction Room 4",
    "The Caves Room 1": "The Caves Room 1",
    "The Caves Room 2": "The Caves Room 2",
    "The Caves Room 3": "The Caves Room 3",
    "The Caves Room 4": "The Caves Room 4",
    "Get A Grip Room 1": "Get A Grip Room 1",
    "Get A Grip Room 2": "Get A Grip Room 2",
    "Get A Grip Room 3": "Get A Grip Room 3",
    "Verticality Room 1": "Verticality Room 1",
    "Verticality Room 2": "Verticality Room 2",
    "Verticality Room 2b": "Verticality Room 2B",
    "Verticality Room 3": "Verticality Room 3",
    "Verticality Room 4": "Verticality Room 4",
    "Catch A Ride Room 1": "Catch A Ride Room 1",
    "Catch A Ride Room 2": "Catch A Ride Room 2",
    "Catch A Ride Room 3": "Catch A Ride Room 3",
    "Catch A Ride Room 4": "Catch A Ride Room 4",
    "Chaos Cavern Room 1": "Chaos Cavern Room 1",
    "Chaos Cavern Room 2": "Chaos Cavern Room 2",
    "Chaos Cavern Room 3": "Chaos Cavern Room 3",
    "Holding On Room 1": "Holding On Room 1",
    "Holding On Room 2": "Holding On Room 2",
    "Holding On Room 3": "Holding On Room 3",
    "Holding On Room 4": "Holding On Room 4",
    "Fist Fight Room 1": "Fist Fight Room 1",
    "Fist Fight Room 2": "Fist Fight Room 2",
    "Fist Fight Room 3": "Fist Fight Room 3",
    "Fist Fight Room 4": "Fist Fight Room 4",
    "Fist Fight Room 5": "Fist Fight Room 5",
    "Fist Fight Boss Arena": "Fist Fight Boss Arena",
    "Depths Room 1": "Depths Room 1",
    "Depths Room 2": "Depths Room 2",
    "Depths Room 3": "Depths Room 3",
    "Cliff Warning Room 1": "Cliff Warning Room 1",
    "Cliff Warning Room 2": "Cliff Warning Room 2",
    "The Library Room 1": "The Library Room 1",
    "The Library Room 1b": "The Library Room 1B",
    "The Library Room 1c": "The Library Room 1C",
    "The Library Room 1d": "The Library Room 1D",
    # World 2
    "Midnight Grove Room 1": "Midnight Grove Room 1",
    "Midnight Grove Room 2": "Midnight Grove Room 2",
    "Midnight Grove Room 3": "Midnight Grove Room 3",
    "Midnight Grove Room 4": "Midnight Grove Room 4",
    "Briarbrush Woods Room 1": "Briarbrush Woods Room 1",
    "Briarbrush Woods Room 2": "Briarbrush Woods Room 2",
    "Briarbrush Woods Room 3": "Briarbrush Woods Room 3",
    "Briarbrush Woods Room 4": "Briarbrush Woods Room 4",
    "Various Explosives Room 1": "Various Explosives Room 1",
    "Various Explosives Room 2": "Various Explosives Room 2",
    "Various Explosives Room 3": "Various Explosives Room 3",
    "Together By Tether Room 1": "Together By Tether Room 1",
    "Together By Tether Room 2": "Together By Tether Room 2",
    "Together By Tether Room 3": "Together By Tether Room 3",
    "Together By Tether Room 4": "Together By Tether Room 4",
    "Pop Unlock Room 1": "Pop Unlock Room 1",
    "Pop Unlock Room 2": "Pop Unlock Room 2",
    "Pop Unlock Room 3": "Pop Unlock Room 3",
    "The Gatekeeper Room 1": "The Gatekeeper Room 1",
    "The Gatekeeper Room 2": "The Gatekeeper Room 2",
    "The Gatekeeper Room 3": "The Gatekeeper Room 3",
    "The Gatekeeper Room 4": "The Gatekeeper Room 4",
    "The Gatekeeper Boss Arena": "The Gatekeeper Boss Arena",
    "The Elevator Room 1": "The Elevator Room 1",
    "The Elevator Room 2": "The Elevator Room 2",
    "The Elevator Room 3": "The Elevator Room 3",
    "Frostbite Room 1": "Frostbite Room 1",
    "Frostbite Room 2": "Frostbite Room 2",
    "Frostbite Room 3": "Frostbite Room 3",
    "Frostbite Room 4": "Frostbite Room 4",
    "Forgotten Archives Room 1": "Forgotten Archives Room 1",
    "Forgotten Archives Room 2": "Forgotten Archives Room 2",
    "Forgotten Archives Room 3": "Forgotten Archives Room 3",
    "Forgotten Archives Room 4": "Forgotten Archives Room 4",
    "Forgotten Archives Room 5": "Forgotten Archives Room 5",
    "The Scenic Route Room 1": "The Scenic Route Room 1",
    "The Scenic Route Room 2": "The Scenic Route Room 2",
    "The Scenic Route Room 3": "The Scenic Route Room 3",
    "The Scenic Route Room 4": "The Scenic Route Room 4",
    "The Scenic Route Room 5": "The Scenic Route Room 5",
    "The Scenic Route Room 6": "The Scenic Route Room 6",
    "The Scenic Route Room 7": "The Scenic Route Room 7",
    # World 3
    "The Timeless Temple Room 1": "The Timeless Temple Room 1",
    "The Timeless Temple Room 2": "The Timeless Temple Room 2",
    "The Timeless Temple Room 3": "The Timeless Temple Room 3",
    "Haunted Halls Room 1": "Haunted Halls Room 1",
    "Haunted Halls Room 2": "Haunted Halls Room 2",
    "Haunted Halls Room 3": "Haunted Halls Room 3",
    "Haunted Halls Room 4": "Haunted Halls Room 4",
    "Borrowed Time Room 1": "Borrowed Time Room 1",
    "Borrowed Time Room 2": "Borrowed Time Room 2",
    "Borrowed Time Room 3": "Borrowed Time Room 3",
    "Borrowed Time Room 4": "Borrowed Time Room 4",
    "Nyctophobia Room 1": "Nyctophobia Room 1",
    "Nyctophobia Room 2": "Nyctophobia Room 2",
    "Nyctophobia Room 3": "Nyctophobia Room 3",
    "Nyctophobia Room 4": "Nyctophobia Room 4",
    "Nyctophobia Room 5": "Nyctophobia Room 5",
    "Shifting Walls Room 1": "Shifting Walls Room 1",
    "Shifting Walls Room 2": "Shifting Walls Room 2",
    "Shifting Walls Room 3": "Shifting Walls Room 3",
    "Shifting Walls Room 4": "Shifting Walls Room 4",
    "Skullduggery Room 1": "Skullduggery Room 1",
    "Skullduggery Room 2": "Skullduggery Room 2",
    "Skullduggery Room 3": "Skullduggery Room 3",
    "Skullduggery Room 4": "Skullduggery Room 4",
    "Skullduggery Room 5": "Skullduggery Room 5",
    "The Throne Room Room 1": "The Throne Room Room 1",
    "The Throne Room Room 2": "The Throne Room Room 2",
    "The Throne Room Room 3": "The Throne Room Room 3",
    "The Throne Room Room 4a": "The Throne Room Room 4A",
    "The Throne Room Room 4b": "The Throne Room Room 4B",
    "The Throne Room Room 5": "The Throne Room Room 5",
    "The Throne Room Room 6a": "The Throne Room Room 6A",
    "The Throne Room Room 6b": "The Throne Room Room 6B",
    "The Throne Room Room 7": "The Throne Room Room 7",
    "The Throne Room Boss Arena": "The Throne Room Boss Arena",
    "The Throne Room Room 8": "The Throne Room Room 8",
    "Pop To The Top Room 1": "Pop To The Top Room 1",
    "Pop To The Top Room 2": "Pop To The Top Room 2",
    "Pop To The Top Room 3": "Pop To The Top Room 3",
    "Periodic Prison Room 1": "Periodic Prison Room 1",
    "Periodic Prison Room 2": "Periodic Prison Room 2",
    "Periodic Prison Room 3": "Periodic Prison Room 3",
    "Periodic Prison Room 4": "Periodic Prison Room 4",
    # World 4
    "Infinity Garden Room 1": "Infinity Garden Room 1",
    "Infinity Garden Room 2": "Infinity Garden Room 2",
    "Infinity Garden Room 3": "Infinity Garden Room 3",
    "Autumnal Aether Room 1": "Autumnal Aether Room 1",
    "Autumnal Aether Room 2": "Autumnal Aether Room 2",
    "Autumnal Aether Room 3": "Autumnal Aether Room 3",
    "Among The Stars Room 1": "Among The Stars Room 1",
    "Among The Stars Room 2": "Among The Stars Room 2",
    "Among The Stars Room 3": "Among The Stars Room 3",
    "Among The Stars Room 4": "Among The Stars Room 4",
    "Den Of Pixies Room 1": "Den Of Pixies Room 1",
    "Den Of Pixies Room 2": "Den Of Pixies Room 2",
    "Den Of Pixies Room 3": "Den Of Pixies Room 3",
    "Den Of Pixies Room 4": "Den Of Pixies Room 4",
    "Heels Over Head Room 1": "Heels Over Head Room 1",
    "Heels Over Head Room 2": "Heels Over Head Room 2",
    "Heels Over Head Room 3": "Heels Over Head Room 3",
    "Heels Over Head Room 4": "Heels Over Head Room 4",
    "The Hive Room 1": "The Hive Room 1",
    "The Hive Room 2": "The Hive Room 2",
    "The Hive Room 3": "The Hive Room 3",
    "The Hive Room 4": "The Hive Room 4",
    "The Hive Room 5": "The Hive Room 5",
    "The Hive Room 6": "The Hive Room 6",
    "The Hive Room 7": "The Hive Room 7",
    "The Five Mile Spire Room 1": "The Five Mile Spire Room 1",
    "The Five Mile Spire Room 2": "The Five Mile Spire Room 2",
    "The Five Mile Spire Room 3": "The Five Mile Spire Room 3",
    "The Five Mile Spire Room 4": "The Five Mile Spire Room 4",
    "The Five Mile Spire Room 5": "The Five Mile Spire Room 5",
    "The Five Mile Spire Room 6": "The Five Mile Spire Room 6",
    "The Five Mile Spire Room 7": "The Five Mile Spire Room 7",
    "The Five Mile Spire Room 7b": "The Five Mile Spire Room 7B",
    "The Five Mile Spire Room 8": "The Five Mile Spire Room 8",
    "Gube Gardens Room 1": "Gube Gardens Room 1",
    "Gube Gardens Room 2": "Gube Gardens Room 2",
    "Gube Gardens Room 3": "Gube Gardens Room 3",
    "Gube Gardens Room 4": "Gube Gardens Room 4",
    "Gube Gardens Room 5": "Gube Gardens Room 5",
    "The Golf Fungus Room 1": "The Golf Fungus Room 1",
    "The Golf Fungus Room 2": "The Golf Fungus Room 2",
    "The Golf Fungus Room 3": "The Golf Fungus Room 3",
    "The Golf Fungus Room 4": "The Golf Fungus Room 4",
    "The Golf Fungus Room 5": "The Golf Fungus Room 5",
    "The Golf Fungus Room 6": "The Golf Fungus Room 6",
    "The Golf Fungus Room 7": "The Golf Fungus Room 7",
    "The Golf Fungus Room 8": "The Golf Fungus Room 8",
    "The Golf Fungus Room 9": "The Golf Fungus Room 9",
    "The Golf Fungus Room 10": "The Golf Fungus Room 10",
    "The Golf Fungus Room 11": "The Golf Fungus Room 11",
    "Over The Woods Room 1": "Over The Woods Room 1",
    "Over The Woods Room 2": "Over The Woods Room 2",
    "Over The Woods Room 3": "Over The Woods Room 3",
    # World 5
    "Welcome To The Void Room 1": "Welcome To The Void Room 1",
    "Welcome To The Void Room 2": "Welcome To The Void Room 2",
    "Welcome To The Void Room 3": "Welcome To The Void Room 3",
    "Welcome To The Void Room 4": "Welcome To The Void Room 4",
    "Welcome To The Void Room 5": "Welcome To The Void Room 5",
    "The Sky Is Falling Room 1": "The Sky Is Falling Room 1",
    "The Sky Is Falling Room 2": "The Sky Is Falling Room 2",
    "The Sky Is Falling Room 3": "The Sky Is Falling Room 3",
    "The Sky Is Falling Room 4": "The Sky Is Falling Room 4",
    "The Sky Is Falling Room 5": "The Sky Is Falling Room 5",
    "The Looking Glass Room 1": "The Looking Glass Room 1",
    "The Looking Glass Room 2": "The Looking Glass Room 2",
    "The Looking Glass Room 3": "The Looking Glass Room 3",
    "The Looking Glass Room 4": "The Looking Glass Room 4",
    "The Looking Glass Room 5": "The Looking Glass Room 5",
    "Galactic Central Point Room 1": "Galactic Central Point Room 1",
    "Galactic Central Point Room 2": "Galactic Central Point Room 2",
    "Galactic Central Point Room 3": "Galactic Central Point Room 3",
    "Galactic Central Point Boss Arena 32": "Galactic Central Point Boss Arena 32",
    "Galactic Central Point Boss Arena 49": "Galactic Central Point Boss Arena 49",
    "Galactic Central Point Boss Arena 37": "Galactic Central Point Boss Arena 37",
    "Universal Bearing Collectible The Hive": "Universal Bearing Collectible The Hive",
    "Universal Bearing Collectible Nyctophobia": "Universal Bearing Collectible Nyctophobia",
    "Universal Bearing Collectible Various Explosives": "Universal Bearing Collectible Various Explosives",
    "Universal Bearing Collectible Introduction": "Universal Bearing Collectible Introduction",
    "Home Room 1": "Home Room 1",
    "Home Room 2": "Home Room 2",
    "Home Room 3": "Home Room 3",
    "Home Room 4": "Home Room 4",
    "Home Room 5": "Home Room 5",
    "Home Room 6": "Home Room 6",
    # Checkpoints
    "Introduction Checkpoint 1": "Introduction Room 3",
    "The Caves Checkpoint 1": "The Caves Room 2",
    "The Caves Checkpoint 2": "The Caves Room 3",
    "Get A Grip Checkpoint 1": "Get A Grip Room 2",
    "Get A Grip Checkpoint 2": "Get A Grip Room 3",
    "Verticality Checkpoint 1": "Verticality Room 2B",
    "Catch A Ride Checkpoint 1": "Catch A Ride Room 3",
    "Holding On Checkpoint 1": "Holding On Room 1",
    "Holding On Checkpoint 2": "Holding On Room 2",
    "Cliff Warning Checkpoint 1": "Cliff Warning Room 2",
    "Midnight Grove Checkpoint 1": "Midnight Grove Room 3",
    "Midnight Grove Checkpoint 2": "Midnight Grove Room 4",
    "Frostbite Checkpoint 1": "Frostbite Room 4",
    "Forgotten Archives Checkpoint 1": "Forgotten Archives Room 2",
    "Forgotten Archives Checkpoint 2": "Forgotten Archives Room 5",
    "Forgotten Archives Checkpoint 3": "Forgotten Archives Room 5",
    "The Scenic Route Checkpoint 1": "The Scenic Route Room 2",
    "Nyctophobia Checkpoint 1": "Nyctophobia Room 4",
    "Shifting Walls Checkpoint 1": "Shifting Walls Room 3",
    "Shifting Walls Checkpoint 2": "Shifting Walls Room 4",
    "Autumnal Aaether Checkpoint 1": "Autumnal Aether Room 1",
    "Autumnal Aaether Checkpoint 2": "Autumnal Aether Room 2",
    "Among The Stars Checkpoint 1": "Among The Stars Room 3",
    "Heels Over Head Checkpoint 1": "Heels Over Head Room 2",
    "The Hive Checkpoint 1": "The Hive Room 2",
    "The Hive Checkpoint 2": "The Hive Room 6",
    "Welcome To The Void Checkpoint 1": "Welcome To The Void Room 3",
    "Welcome To The Void Checkpoint 2": "Welcome To The Void Room 4",
    "The Looking Glass Checkpoint 1": "The Looking Glass Room 5",
    "Galactic Central Point Checkpoint 1": "Galactic Central Point Boss Arena 49",
    "Universal Bearing Collectable Checkpoint 1": "Universal Bearing Collectible The Hive",
    "Universal Bearing Collectable Checkpoint 2": "Universal Bearing Collectible Nyctophobia",
    "Universal Bearing Collectable Checkpoint 3": "Universal Bearing Collectible Various Explosives",
    "Universal Bearing Collectable Checkpoint 4": "Universal Bearing Collectible Introduction",
    "Home Checkpoint 1": "Home Room 2",
    "Home Checkpoint 2": "Home Room 2",
    "Home Checkpoint 3": "Home Room 2",
    "Home Checkpoint 4": "Home Room 2",
    "Home Checkpoint 5": "Home Room 2",
    "Home Checkpoint 6": "Home Room 3",
    "Home Checkpoint 7": "Home Room 3",
    "Home Checkpoint 8": "Home Room 3"
}

class FantasticFistLocation(Location):
    game = "Fantastic Fist"

def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
    return {location_name: LOCATION_NAME_TO_ID[location_names] for location_name in location_names}

def create_all_locations(world: FantasticFistWorld) -> None:
    create_coin_locations(world)
    create_exit_locations(world)
    create_tutorial_locations(world)
    create_boss_locations(world)
    create_room_locations(world)
    create_checkpoint_locations(world)

def create_location(world: FantasticFistWorld, location_id: int) -> None:
    region_name: str = ID_TO_LOCATION_NAME[location_id]
    location_name: str = LOCATION_NAME_TO_REGION[region_name]

    region = world.get_region(region_name)

    location = FantasticFistLocation(world.player, location_name, world.location_name_to_id[location_name], region)

    region.locations.append(location)

def create_locked_location(world: FantasticFistWorld, location_id: int, item_name: str):
    region_name: str = ID_TO_LOCATION_NAME[location_id]
    location_name: str = LOCATION_NAME_TO_REGION[region_name]

    region = world.get_region(region_name)

    location = FantasticFistLocation(world.player, location_name, world.location_name_to_id[location_name], region)

    location.place_locked_item(world.create_item(item_name))

    region.locations.append(location)

def create_coin_locations(world: FantasticFistWorld) -> None:
    create_location(world, (k for k in range(1, 101)))

def create_exit_locations(world: FantasticFistWorld) -> None:
    if world.options.paths == 0:
        #Vanilla paths
        for location_id in range(130, 182):
            exit_region: str = LOCATION_NAME_TO_REGION[ID_TO_LOCATION_NAME[location_id]]
            level_id: str = ""
            if exit_region == "The Library Room 1":
                for entrance in world.randomized_entrances:
                    if entrance.end_node.node_name == "The Library Room 1":
                        level_id = entrance.start_node.node_name
            else:
                current_region: str = exit_region
                has_earlier_room: bool = True
                while has_earlier_room:
                    has_earlier_room = False
                    for door in world.randomized_doors:
                        if door.end_node.node_name == current_region:
                            current_region = door.start_node.node_name
                            has_earlier_room = True
                            break
                for entrance in world.randomized_entrances:
                    if entrance.end_node.node_name == current_region:
                        level_id = entrance.start_node.node_name
            
            if level_id == "1-0" or level_id == "5-4":
                # Neither Galactic Central Point nor Home have paths
                create_location(world, location_id)
            elif location_id == 179:
                # Handle the path to Home
                if world.options.goal == 2 or world.options.open_world <= 1:
                    create_locked_location(world, location_id, "1-1 Home Exit Path")
                else:
                    create_location(world, location_id)
            elif (level_id == "1-8" or
                  level_id == "2-6" or
                  level_id == "2-D" or
                  level_id == "3-7" or
                  level_id == "4-9"):
                # Handle boss levels (and The Scenic Route)
                if world.options.open_world <= 2:
                    level_path: str = level_id + " Boss Exit Path"
                    if level_id == "2-D":
                        level_path = "2-D Standard Exit Path"
                    create_locked_location(world, location_id, level_path)
                else:
                    create_location(world, location_id)
            elif (location_id == 132 or
                  location_id == 135 or
                  location_id == 144 or
                  location_id == 153 or
                  location_id == 156 or
                  location_id == 166):
                # Handle secret exits
                if world.options.open_world <= 1:
                    level_path: str = level_id + " Secret Exit Path"
                    create_locked_location(world, location_id, level_path)
                else:
                    create_location(world, location_id)
            elif (level_id == "1-A" or
                  level_id == "1-B" or
                  level_id == "1-C" or
                  level_id == "2-A" or
                  level_id == "2-B" or
                  level_id == "2-C" or
                  level_id == "3-A" or
                  level_id == "3-B" or
                  level_id == "4-A"):
                # Handle exits in secret levels
                if world.options.open_world <= 1:
                    level_path: str = level_id + " Standard Exit Path"
                    create_locked_location(world, location_id, level_path)
                else:
                    create_location(world, location_id)
            else:
                # Handle standard exits
                if world.options.open_world <= 0:
                    level_path: str = level_id + " Standard Exit Path"
                    create_locked_location(world, location_id, level_path)
                else:
                    create_location(world, location_id)
    else:
         for location_id in range(130, 182):
            if location_id == 179 and world.options.goal == 2:
                create_locked_location(world, 179, "1-1 Home Exit Path")
            else:
                create_location(world, location_id)

def create_tutorial_locations(world: FantasticFistWorld) -> None:
    create_location(world, (k for k in range(200, 206)))
    create_location(world, (k for k in range(250, 257)))

def create_boss_locations(world: FantasticFistWorld) -> None:
    create_location(world, (k for k in range(300, 343)))

def create_room_locations(world: FantasticFistWorld) -> None:
    if world.options.roomsanity:
        create_location(world, (k for k in range(400, 442)))
        create_location(world, (k for k in range(500, 542)))
        create_location(world, (k for k in range(600, 643)))
        create_location(world, (k for k in range(700, 753)))
        create_location(world, (k for k in range(800, 831)))

def create_checkpoint_locations(world: FantasticFistWorld) -> None:
    if world.options.checkpointsanity:
        create_location(world, (k for k in range(900, 942)))